### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by skippa** [rvs/libnxt#2]
Hi there,

I ran `scons` in the `libnxt` directory after cloning, got this error 
`lowlevel.c:29:10: fatal error: usb.h: No such file or directory`
`29 | #include <usb.h>`

I'm on Arch Linux, libusb-1.0.23-2 is installed as is scons-3.1.2-2 and recently updated my system

Any ideas how can I fix this?

Thanks in advance :)  Very keen to get an old NXT 2.0 I bought for my son up and running!

**Comment by rvs** [comment]
Hey @skippa -- would love to know if you were able to solve your problem. If not -- just let me know and I may try to update the repo with a Dockerfile that helps build it.

**Comment by skippa** [comment]
Nah, I think it's because the newer libraries don't work and it's hard to roll back without breaking a bunch of other stuff on my system ;) Ideally I'd really like to compile this for Arch with a PKGBUILD but if that's not possible then yeah a docker would be great!

**Comment by rvs** [comment]
Hey @skippa -- I've just pushed this extra commit https://github.com/rvs/libnxt/commit/f8bc591919037e177416544d4ced99913768e933#diff-c47c7c7383225ab55ff591cb59c41e6bR1

Can you please give it a try and let me know if that works for you.

**Comment by skippa** [comment]
Cool thanks man, I'll have a crack at it tonight and tell you how it goes

**Comment by rvs** [comment]
Any luck @skippa ?

**Comment by skippa** [comment]
Argh crap, sorry mate totally forgot. Will def get on this tonight ;)

**Comment by skippa** [comment]
Sweet, yep both fwexec and fwflash were compiled (with a few warnings) and they both seem to execute fine though I haven't actually used them to flash my NXT yet.

Thanks heaps!

**Comment by rvs** [comment]
Awesome! Closing this one then as resolved
